### ISSUE TITLE
Negotiation process freezes on the consumer side

### ISSUE THREAD

**Issue by ip312** [sovity/edc-extensions#139]
# Bug Report

## Description

![grafik](https://user-images.githubusercontent.com/91048868/220948221-cd559fde-23ea-4460-9a7f-5c6ed7232944.png)

### Expected Behavior

Consumer is able to negotiate the offer and to consume the data asset. 

### Observed Behavior

The asset window freezes during the negotiation process. 

1. **Provider**
CaaS Connector  
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F-958678592
Asset: 
https://catalog.test.mobility-dataspace.eu/resources/resource?id=https://broker.test.mobility-dataspace.eu/catalog/-958678592/1598247006/-1999792879
Policy: 
```
[
  {
    "edctype": "dataspaceconnector:permission",
    "uid": null,
    "target": null,
    "action": {
      "type": "USE",
      "includedIn": null,
      "constraint": null
    },
    "assignee": null,
    "assigner": null,
    "constraints": [
      {
        "edctype": "AtomicConstraint",
        "leftExpression": {
          "edctype": "dataspaceconnector:literalexpression",
          "value": "POLICY_EVALUATION_TIME"
        },
        "rightExpression": {
          "edctype": "dataspaceconnector:literalexpression",
          "value": "2023-02-14T23:00:00.000Z"
        },
        "operator": "GT"
      },
      {
        "edctype": "AtomicConstraint",
        "leftExpression": {
          "edctype": "dataspaceconnector:literalexpression",
          "value": "POLICY_EVALUATION_TIME"
        },
        "rightExpression": {
          "edctype": "dataspaceconnector:literalexpression",
          "value": "2023-12-30T23:00:00.000Z"
        },
        "operator": "LT"
      }
    ],
    "duties": []
  }
]
```
2.  **Consumer:**
The Docker container deployed locally
- registered at the broker
- is able to publich a contract offer at the broker

3.  Go to Consumer/Catalog Browser

4. Insert as Connector IDs: `https://connector-mds-test-001.prod-sovity.azure.sovity.io/control/api/v1/ids/data `

![grafik](https://user-images.githubusercontent.com/91048868/220966088-300522ca-02e5-499a-bae8-5b15c4adbdbd.png)

5. Click on MDS Demo Asset

6. Click on ` Negotiate`

**Comment by SebastianOpriel** [comment]
Hi @ip312, the connector hosted online (provider) would need to send a contract agreement to the other connector. As you host it locally, the provider tries to send ContractNegotiation to http://localhost:4317 which does not work. Please supply your local connector with a valid URL or IP which is reachable from the internet.
In case you have further questions, please reopen the issue.
