### ISSUE TITLE
Provide OpenAPI definition and extensive Postman collection

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#152]
# Feature Request

## Description
To interact with the EDC it would be great to have
- [x] OpenAPI definition in place (at docs?) https://github.com/sovity/edc-extensions/pull/178
- [ ] extensive Postman collection, which is at least capable of requesting catalogs, negotiating contracts and transfer data. @tmberthold

**Comment by tmberthold** [comment]
I add an extended Postman Collection through the following PR, is an example of an HTTP pull. Requires 2 EDC for Contract Negotiation and co, therefore separate file.
https://github.com/sovity/edc-extensions/pull/153

**Comment by efiege** [comment]
[Control-Plane-Open-API](https://github.com/sovity/EDC-deployments/blob/8fe50b1f6d4550ea1df4ab60808755ce018f7ab8/launchers/sovity-control-plane/openapi.yaml)
[Data-Plane-Open-API](https://github.com/sovity/EDC-deployments/blob/8fe50b1f6d4550ea1df4ab60808755ce018f7ab8/launchers/sovity-data-plane/openapi.yaml)

**Comment by tmberthold** [comment]
The extended postman collection will come together with the Milestone 8 PR because endpoints will change....
