### ISSUE TITLE
One asset and two contract definitions become four contract offers

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#169]
# Bug Report

## Description

When giving an asset two contract definitions and loading your own assets you get four contract offers in the catalog browser.

### Expected Behavior

You should get two-

Right now you can't see a contract offer's policy yet, but you will with https://github.com/sovity/edc-ui/issues/164

Then it would make sense to see the same asset with different policies as contract offers.

## Context Information

Version of sovity edc product release 06.03.2023

**Comment by ip312** [comment]
I can confirm it.

**Comment by richardtreier** [comment]
This bug seems to have disappeared in MS8. Please re-open if the issue persists.
