### ISSUE TITLE
Readme: Remove manually determining SKI AKI 

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#19]
# Feature Request

## Type of Issue
Cleanup

## Describe the ideal solution or feature request
- [x] Remove Option B https://github.com/sovity/edc-extensions#option-2-manually-with-keystore-explorer
- [x] Keep other parts of the Readme.md consistent
- [x] Add hint with regards to necessary command line packages (openssl, keytool) and wsl/linux

**Comment by omarsilva1** [comment]
Are you sure we want to delete that? If the user doesnt have WSL he woundnt be able to generate the keys as its a bash script

**Comment by SebastianOpriel** [comment]
As this step is error prone, I would rely on a linux shell. Please also add hint for required packages and wsl/linux.

**Comment by ip312** [comment]
I would add that under Windows e.g. Git Bash can be used. I tested the script with Git Bash and it works fine.

**Comment by omarsilva1** [comment]
Did the script also generate the .jks file with git bash?

**Comment by ip312** [comment]
Yes, it did.

**Comment by omarsilva1** [comment]
> Yes, it did.

Interesting, I will add this to the README
