### ISSUE TITLE
Wrong "Transfer complete" message

### ISSUE THREAD

**Issue by ip312** [sovity/edc-extensions#262]
# Bug Report

If a contract exists between a data provider and a data consumer, afterwards the data provider deletes the contract definition and the consumer tries to consume a data asset, the consumer frontend presents a "transfer complete" message and the transfer history contains the following entry
![grafik](https://user-images.githubusercontent.com/91048868/230111872-4ffa7d07-96f9-4417-8b63-b00faff112de.png)

### Expected Behavior

Error message on the frontend, no entry in the transfer history.

### Observed Behavior

S. above

## Steps to Reproduce

1. Provider Connector publisches a contract definition with Always Free Policy
2. Consumer Connector negotiates a contract
3. (optional) Consumer Connector consumes a data asset.
4. Provider Connector deletes the contract definition
5. Consumer Connector tries to consume the data asset.

**Comment by AnurosePrakash** [comment]
@ip312 As of now, there are no transfer complete messages in the consumer UI in cases when the contract definition is deleted at the provider side, Can you please confirm if the issue still persists?

**Comment by ip312** [comment]
Closed.
