### ISSUE TITLE
Broker deregistration after connector shutdown seems not to work properly

### ISSUE THREAD

**Issue by ip312** [sovity/edc-extensions#266]
# Bug Report

## Description

After shutdown of the connector I can further see it on the MDS test broker.
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F457711283

### Expected Behavior

After shutdown the connector is not visible on the broker anymore.

### Observed Behavior

It is visible.

## Steps to Reproduce

1. Start the local connector in the docker desktop
2. Check, whether the connector is registered on the broker (yes)
3. Shutdown the connector in the docker desktop
4. Check, whether the connector is deregistered (no) 

## Context Information

- Environment: Local
- Used version: 3.0.1

**Comment by tmberthold** [comment]
Wild guess - maybe something with the DAT:

Current (EDC Milestone 8) IDS-tokenvalue (plain json) send to the IDS-Broker:
![image](https://user-images.githubusercontent.com/75306992/231669420-f9ea0ee0-0da3-475f-94db-4a36b72241c6.png)

vs. expected tokenvalue (jwt):
![image](https://user-images.githubusercontent.com/75306992/231672636-19f9b039-f246-42a1-a1e9-a3b8e4a42dbf.png)

We'll keep looking at this...

**Comment by SebastianOpriel** [comment]
@ip312 can you clarify on your latest observations regarding the Broker? Does this correlate with this issue?

**Comment by ip312** [comment]
My assumption is that there are two different things. 
At the time i noticed the issue above I was able to register connectors, e.g.
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F457711283
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F-1765550025
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F-1865489203
which were not deregistered after shutdown of these connectors in the docker desktop.

Currently I am not able to register connectors due to the mentioned response problem at the Broker.

**Comment by ip312** [comment]
Now I can confirm the issue. I have just started the docker desktop and registered this connector 
https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F457711283
After that I have stopped the docker container via docker desktop, but as you can see, the connector is still registered.

**Comment by SebastianOpriel** [comment]
@ip312 wrote:

> The deregistration problem seems to be still there. Started the 3.1.0. version now, the connector reported to the broker, now I stopped that, but it is still there. https://catalog.test.mobility-dataspace.eu/connector/connector?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F457711283 . 
> Branch 3.1.0 is missing, so I took main

- [ ] Create branch 3.1.0
