### ISSUE TITLE
Problems while generating .jks

### ISSUE THREAD

**Issue by jomes-db** [sovity/edc-extensions#267]
# Bug Report

## Description

We downloaded the MDS Certificate and got a Zip-File containing a `p12`, `key` and a `crt` file.
Then we tried to generate a `jks`file with the provided script found under `docs/getting-started/secrets`
To our surprise we were asked for a password, which was not provided to us at any point.

### Expected Behavior

We expected to get a jks file without any passwords

### Observed Behavior

The Error we got by providing an new password was the following:

````
Mac verify error: invalid password?
unable to load certificate
140704658769536:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/pem/pem_lib.c:694:Expecting: TRUSTED CERTIFICATE
keytool error: java.io.IOException: keystore password was incorrect
:keyid:
````

## Context Information

_Add any other context about the problem here._

- Used version: latest
- OS: MacOS

**Comment by ip312** [comment]
The default certificate password is password

**Comment by avogadriholonix** [comment]
The .p12 file should already be a keystore... you shouldn't need to create
a .jks file. For what is my knowledge keytool doesn't allow to create a
store with an empty password.
I suggest you to put the .p12 file in the vault location and use it.

**Comment by SebastianOpriel** [comment]
A p12 file is indeed a keystore, but not in the needed format for EDCs. Thus, you have to convert it to a jks (Java Key Store) and place it as "keystore.jks" at `/docs/getting-started/secrets`. It then gets automatically mounted by docker-compose.

To generate a jks from a p12, you can use `docs/getting-started/secrets/generate_ski_aki.sh`. As @ip312 said, the default password of the p12 is `password`. The same password is used for generating a jks.
