### ISSUE TITLE
Postman Collection Old Stuff / README.md misaligned

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#278]
# Bug Report

## Description

Some contents of our postman collection are either part of the old postman collection or the README.md contains errors.

## Stakeholders
MDS

**Comment by tmberthold** [comment]
Can we get a little more background info on this? Right off the bat I can't find any errors....

**Comment by ip312** [comment]
Just slight inconsistencies: _[Publish Asset 1](https://github.com/sovity/edc-extensions/blob/main/docs/getting-started/README.md#postman-collection)_ vs. _[1 Create Asset](https://github.com/sovity/edc-extensions/blob/main/docs/postman_collection.json)_ and so on
