### ISSUE TITLE
Missing STYLEGUIDE.md

### ISSUE THREAD

**Issue by Krieke** [sovity/edc-extensions#292]
# Bug Report

## Description
The `CONTRIBUTING.md` section [Adhere to Coding Style Guide](https://github.com/sovity/edc-extensions/blob/main/CONTRIBUTING.md#adhere-to-coding-style-guide) has a link with name `styleguide` with a destination anchor to a `STYLEGUIDE.md` source that doesn't exist in the project.

The CONTRIBUTING.md contains more references to this STYLEGUIDE.md

### Expected Behaviour
That the `styleguide` source anchor would have an existing destination anchor source `STYLEGUIDE.md` or that this section is being removed from the document.

### Observed Behaviour
Broken link due to missing source for the configured the destination anchor.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Open 'CONTRIBUTING.md'
2. Go to '###adhere-to-coding-style-guide'
3. Click on 'styleguide'
4. See error 404 not found

## Context Information
main branch during issue creation

## Possible Implementation and Work Breakdown

-   [ ] Add a STYLEGUIDE.md in the root of the project containing the expected coding style details for this project.

**Comment by SebastianOpriel** [comment]
Please have a look here and maybe copy the missing file: https://github.com/sovity/github-repo-template
