### ISSUE TITLE
Migrate documentation to gitbook

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#389]
# Feature Request

## Description
We want to use gitbook to build a readable and integratable website for the documentation. Steps for proper configuration can be found here: https://docs.gitbook.com/product-tour/git-sync/content-configuration

## Description
The core EDC documentation is not sufficiently customer focused.
At sovity we want to improve the experience for our customer. 

## Goal
Move from README in GitHub to gitbook

## Task Breakdown

- [ ] Present documentation approach to the team @tmberthold will share with @AbdullahMuk. @AbdullahMuk will define how best to communicate. Cross-check with business team the scope to which it needs to be involved in the approach. 
- [ ] https://github.com/sovity/edc-extensions/issues/594

**Comment by tmberthold** [comment]
Documentation is a highly discussed topic but we have made great and valuable progress since the issue was originally created. The issue itself should be outdated by now.
