### ISSUE TITLE
Better Deployment Documentation for Community Edition

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#390]
# Feature Request

## Description

The multiple port problem makes deploying the sovity EDC Community Edition hard to explain.

As a first step we should add a better deployment documentation:

Similar to https://github.com/sovity/edc-broker-server-extension/#reverse-proxy-configuration, except without the /backend.

**Comment by AbdullahMuk** [comment]
Covered in docs/deployment-guide/goals/production
