### ISSUE TITLE
Last Commit Info not reaching UI

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#420]
# Bug Report

## Description

We have a backend extension that should pipe the contents of [extensions/last-commit-info/src/main/resources](https://github.com/sovity/edc-extensions/tree/main/extensions/last-commit-info/src/main/resources) into a rest request.

When using the [docker-compose-dev.yaml](https://github.com/sovity/edc-extensions/tree/main/docker-compose-dev.yaml), the backend responds with this:

```json 
{
  "envLastCommitInfo": "\"commit d2fd35a84ede3c9303bb14f4a20712dcca84ceed",
  "envBuildDate": "\"2023-07-06T07:16:52Z\"",
  "jarLastCommitInfo": "The GitHub Pipeline will replace this file during build time with\nthe commit information (SHA, author and commit message) of the built image.\nThis file will be served to allow checking for the exact source code version of a deployed edc-ui.",
  "jarBuildDate": "The GitHub Pipeline will replace this file during build time with the current date."
}
```

## Breakdown
- [ ] Add the  [writing of the files for the Jar version info](https://github.com/sovity/edc-extensions/blob/main/.github/workflows/build-and-publish-maven-artifacts.yml#L37C1-L40C103) in the [publish images pipeline](https://github.com/sovity/edc-extensions/blob/main/.github/workflows/build-and-publish-connector-images.yml#L52C1-L59C65)
- [ ] Debug / Analyze why the [set env variables](https://github.com/sovity/edc-extensions/blob/main/.github/workflows/build-and-publish-connector-images.yml#L52C1-L59C65) are not available in the [running images as env variables](https://github.com/sovity/edc-extensions/blob/main/extensions/last-commit-info/src/main/java/de/sovity/edc/extension/LastCommitInfoService.java#L43C1-L45C6)

**Comment by AbdullahMuk** [comment]
To be checked after Product Release for EDC 0.2.0

**Comment by richardtreier** [comment]
implementation should be done
