### ISSUE TITLE
Add Policy Page to the API-Wrapper

### ISSUE THREAD

**Issue by efiege** [sovity/edc-extensions#431]
# Feature Request

## Description
Create a `GET` method in the `UiResource`, which will return all necessary information needed by the policy page of the ui.

## Solution Proposal and Work Breakdown
- [x] Use already existing page calls as template
- [x] Evaluate on which information the policy page depends on
- [x] Create a model for the information
- [x] Create the `GET` Method, returning all required information

**Comment by richardtreier** [comment]
duplicate of https://github.com/sovity/edc-ui/issues/410
