### ISSUE TITLE
Add Contract Definition Page to the API-Wrapper

### ISSUE THREAD

**Issue by SaadEGI** [sovity/edc-extensions#461]
# Feature Request

## Description

Create a GET method in the UiResource, which will return all necessary information needed by the Contract Definition page of the ui.

## Solution Proposal and Work Breakdown

- [ ] Use already existing page calls as template
- [ ] Evaluate on which information the Contract Definiton page depends on
- [ ] Create a model for the information
- [ ] Create the GET Method, returning all required information

**Comment by richardtreier** [comment]
Old issue, already implemented.
