### ISSUE TITLE
Display Transfer Processes Sorted By Date

### ISSUE THREAD

**Issue by efiege** [sovity/edc-extensions#508]
# Feature Request

## Description

The transfer-processes are displayed in a random order. They should be sorted by the last updated field, with the most recent update on the top.
```[tasklist]
### Tasks
- [ ] fix the transfer process order
- [ ] add tests testing for that order
```

**Comment by AbdullahMuk** [comment]
Richard will review the pull request so that we can assess if we can close the issue.

**Comment by richardtreier** [comment]
Seems to be fixed in production. Idk
