### ISSUE TITLE
Wrong transfer state

### ISSUE THREAD

**Issue by FlorianJa** [sovity/edc-extensions#576]
# Bug Report

## Description

In the v5.0.0 release/tag the transfer state does not transitioning to the complete state. There is a message in the connector log: 
`2023-10-16 15:27:40 No checker found for process 3c4553ac-2b40-4f1a-9200-f4951a500096. The process will not advance to the COMPLETED state.`
The wrong state is also propagated into the UI. The state stays on Started also showing some animations.

This is a known issuse of the EDC version 0.2.1 that was fixed with v0.3.0. 
https://github.com/eclipse-edc/Connector/issues/3334 

I think is not a major issue but should be mentioned as known issue in the release notes.

**Comment by richardtreier** [comment]
Thank you for the issue. 

Once we bump the Eclipse EDC to a higher version, we'll be able to confirm by tests, whether the issue will have disappeared.

**Comment by richardtreier** [comment]
Fix implemented in https://github.com/sovity/edc-extensions/pull/653, please wait for the upcoming release for a fixed version.
