### ISSUE TITLE
sovityEdcExtensionsVersion not up-to-date

### ISSUE THREAD

**Issue by bearn01d** [sovity/edc-extensions#580]
# Bug Report

## Description

The property `sovityEdcExtensionsVersion` in `gradle.properties` is set to 0.0.1-SNAPSHOT. This prevents installing the extensions to a local Maven repository and subsequently referencing them with the overall current version number, i.e. 5.0.0.
This has been introduced with the release of v4.2.0, in https://github.com/sovity/edc-extensions/commit/17ea85d89ccda2a345ac6f5c82cd700ca608fe20.

### Expected Behavior

The sovity EDC extensions are built with the version number matching the sovity EDC release.

### Observed Behavior

The sovity EDC extensions version number is 0.0.1-SNAPSHOT.

**Comment by richardtreier** [comment]
Hi, there is only one snapshot version of edc-extensions at all times, which is the latest version of the main. Consumers of edc-extensions may rely on the release versions. Thus, releases will have their gradle version overridden.

For local repository-spanning development there is no special support.
