### ISSUE TITLE
Double encoding of datasource url query parameters

### ISSUE THREAD

**Issue by ip312** [sovity/edc-extensions#582]
Issue
------

Datasource URL parameters on an asset appear to be url-encoded twice, resulting in invalid queries at the datasource.

Steps:

1. I have a datasource that accepts a date query parameter in the format `2023-10-13T00:00:00.000Z`
2. Using the mds ui dashboard I added an asset that had a query parameter name: `since`, value: `2023-10-13T00:00:00.000Z`
3. Set up a contract for the asset using the open policy
4. Negotiated and attempted a transfer using a different broker

The transfer failed, with the datasource reporting bad-request. The query received by the datasource was `https://...?since=2023-10-13T00%3A00%3A00.000Z`

which appeared to be the datasource not decoding the url. However, the ingress logs showed the inbound request as 

`https://...?since=2023-10-13T00%253A00%253A00.000Z`

indicating that the '%' char has been url encoded. Looking at the EDC database table `edc_assets_dataaddress`  the query parameter is stored in it's url encoded form as `2023-10-13T00%3A00%3A00.000Z`

So it appears that the url is being encoded twice: once when being stored in the edc database, then again when being sent to the datasource.

Expected Result
-----------------

The datasource ingress receives `https://...?since=2023-10-13T00%3A00%3A00.000Z`, which can be correctly decoded to `https://...?since=2023-10-13T00:00:00.000Z`

#https://github.com/Mobility-Data-Space/mobility-data-space/issues/30

### Check whether issue lies within core EDC

```[tasklist]
- [x] Add another endpoint that accepts queryParams to `TestBackendController`
- [x] Implement an end-to-end test between two connectors that uses queryParams with special chars for the DataAddressProperties of the data source
- [x] Verify that the mock endpoint is called with double encoded queryParams (this indicates that the issue lies within EDC)
- [x] Afterward, add `testThatQueryParamsAreNotWorking` which will turn red once EDC bug is fixed
- [ ] Create new issue, link new issue in customer issue, create edc issue, add known issues in release
```

### Quick fix in the edc-ui

```[tasklist]
- [x] Remove URI encoding
- [x] Add form validation to not allow "=" chars within the key and value fields of queryParams
```

**Comment by tmberthold** [comment]
Just to summarize the problem for further understanding:
- user adds query parameters to an asset's datasource information via sovity mds edc-ui: `since` with value `2023-10-13T00:00:00.000Z`
- EDC saves it in its database table `edc_assets_dataaddress` as `2023-10-13T00%3A00%3A00.000Z` (encoded x1)
- when using the asset's datasource information it ends up being at the ingress of the datasource itself: `2023-10-13T00%253A00%253A00.000Z` (encoded x2)
- encoding x1 would not be a problem for the actual data source

Correct?

**Comment by richardtreier** [comment]
@illfixit is checking for frontend issues. after that we can proceed with checking for backend issues.
