### ISSUE TITLE
Add new MDS attributes in EDC and convert new attributes to DCat + implement in the EDC and broker.

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#602]
# Feature Request

## Description

As a a shareholde of the MDS and a user of the MDS EDC, I want to define my assets with specific attributes to achieve interoperability with Mobilithek. 

We have been provided with a list of attributes the assets in our EDC need to contain. The new attributes must be converted to DCat and implemented in the EDC and broker.
The list of new attributes (asset properties) was sent to sovity on 28 September.

1.	Sovereign (Text Field, 0...1)To distinguish between publisher and sovereign
2.	GeoLocation (Text Field, 0...1)
3.	NUTS Location (Text Field, 0…n)
4.	Data Sample (URL, 0…n) [later: with the possibility to upload files]
5.	Reference Files/Schemas (URL, 0…n)
6.	Additional Description (Text Area, 0…1) Additional Information on Reference Files/Schemas
7.	ConditionForUse/Notes (Text Area, 0…1)
8.	Data update frequency (Text Field, 0…1)
9.	Temporal Coverage (1 or 2 DateTime, 0…1) start and stop time, it should be possible to select just one attribute. No dependency to time restricted policy.

Only for the Broker:
B1. Last Description Update (DateTime, 1, generated automatically)

## Which Areas Would Be Affected?

- edc-extensions
- edc-ui (Connector UI + Broker UI)
- edc-broker-extension

## Why Is the Feature Desired?

_What problems does that user face that existing functionalities do solve?_
Solution will enable compatibility with assets located in Mobilithek.
To be further detailed based on details provided by JQ in the description section. @AbdullahMuk 

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

- Enhancement of MDS variant of the sovity product
- General enhancement of the sovity product based on same principle as first wave of MDS attributes that were added in the past.

## Stakeholders
- MDS
- @jkbquabeck 
- @SebastianOpriel 
- @sebk46 

## Solution Proposal and Work Breakdown

```[tasklist]
### EDC Extensions
- [x] Prerequisite: Ask MDS for additional data regarding the values of the above fields. We need more descriptions on possible validations, etc. Is it required for e.g. the geo location to be in a specific format? Should you be able to paste in an address? These are all non-trivial questions.
- [x] New MDS Asset Metadata needs to be added. Affected: UiAsset, UiAssetCreateRequest, UiAssetEditMetadataRequest, UiAssetMapper, `Prop.Mds` Class
- [x] Write database migration changing existing MDS attribute keys
```

```[tasklist]
### Broker Server
- [x] Bump edc-extensions version
```

```[tasklist]
### EDC UI
- [x] Connector UI: Integrate new fields into Asset Creation process (also check other variants afterwards, **this is a large task due to the fields above being sometimes more complicated**)
- [x] Connector UI: Show new MDS Asset Metadata in Asset Detail Dialog, Contract Offer Detail Dialog, Contract Agreement Detail Dialog, this might need layout changes, hiding non-set attributes, switching to a page
- [x] Broker UI: Show new MDS Asset Metadata in Data Offer Details
```

**Comment by richardtreier** [comment]
Notes regarding estimation:
![grafik](https://github.com/sovity/edc-extensions/assets/30114507/4a936795-eb6b-4cea-8b32-2db4a03e1092)

**Comment by jkbquabeck** [comment]
@AbdullahMuk We need to keep in mind that these new asset porperties need to be displayed in the broker as well. So on end of January we will need to release EDC CE, Broker and Authority Portal to remain compatible

**Comment by richardtreier** [comment]
- The following Attributes are no problem:
  - [x] Sovereign (Text Field, 0...1) Um zwischen Publisher and Sovereign zu unterscheiden.  
    - Simple text input
  - [x] NUTS Location (Text Field, 0…n)
    - Multiple text inputs
  - [x] Data Sample (URL, 0…n) Später auch mit Möglichkeit Dateien hochzuladen
    - If simple URL: Multiple text inputs
  - [x] GeoLocation (Text Field, 0...1)
    - Simple text input
  - [x] Reference Files/Schemas (URL, 0…n)
    - Multiple text inputs with URL validation
  - [x] Reference File "Additional Description" (Text Area, 0…1) Zusätzliche Information betr. Reference Files/Schemas
    - Multi-line Text field
- Fields with some notes, @ip312, could you please check if this is all fine?
  - [ ] Data update frequency (Text Field, 0…1)
    - Does this have a Unit?
    - Otherwise this will become a Simple Text Input without validation
  - [ ] ConditionForUse/Notes (Text Area, 0…1)
    - Multi-line Text field
    - This will be duplicated with the license URL field that we already have, if that is alright, it will be rather be called "license text" with more description regarding "conditions for use"
  - [ ] Temporal Coverage (1 oder 2 DateTime, 0…1) Start und Stop Time, mit Möglichkeit nur ein Attribut auszuwählen. Keine Abhängigkeit von Time Policy.
    - This will be different from the date pickers used so far due to it being date-times, and not just dates, so input might be a little trickier.
    - In fact, this might be coded to support time zones and display dates in the current time zone.
- [ ] @ip312, could you maybe provide for each field an example value and a description text? I would need those to check if the fields will truly contain what they are called right now to prevent generalizing them while they are used for specific things in the Mobilithek.

**Comment by ip312** [comment]
@richardtreier thank you.
Let us take one step back and start with the existing mobility releavnt attributes, which are currently mapped as follows:
    _"http://w3id.org/mds#dataCategory": "unchanged",
    "http://w3id.org/mds#dataSubcategory": "unchanged",
    "http://w3id.org/mds#dataModel": "unchanged",
    "http://w3id.org/mds#geoReferenceMethod": "unchanged",
    "http://w3id.org/mds#transportMode": "unchanged"_

In the meantime the new speicfication [MobilityDCAT](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html) was published and I would prefer to use the standardised attributes, which would be:
**https://w3id.org/mobilitydcat-ap/mobility-theme** for DataCategory and DataSubcategory
**https://w3id.org/mobilitydcat-ap/mobility-data-standard
https://w3id.org/mobilitydcat-ap/georeferencing-method
https://w3id.org/mobilitydcat-ap/transport-mode**

Are we able to use this new spec in the MDS 2.1. version?

**Comment by ip312** [comment]
@richardtreier  
**Data update frequency**
I saw that there is a controlled vocabulary for this in the mobilityDCAT spec, but let us start with Simple Text Input without validation.

**Temporal Coverage**
You are right, I didn't consider this aspect.  Let us start just with Date without Time and re-use the existing implementation.

**ConditionForUse/Notes** 
Multi-line Text field

There is no duplication, because the license field is for the legally relevant license and this one for additional (not legally relevant) conditions, s. Mobilithek-Example:
![grafik](https://github.com/sovity/edc-extensions/assets/91048868/aa469caf-bed5-4551-b1fb-35a49f0d0c25)

Please use the mobilityDCAT spec for the mapping (where applicable)

**Comment by richardtreier** [comment]
Alright, thanks for the update! @ip312

**Comment by kulgg** [comment]
Summarizing all this

### New Asset fields

| Name | Data Type | Cardinality | Notes | DCAT |
|---|---|---|---|---|
| Sovereign  |  Text Field |  0..1  |  Distinguish between publisher and sovereign |   |
| GeoLocation | Text Field  |  0..1 |   |   |
| NUTS Location |  Text Field | 0..n  |   |   |
| Data Sample | URL | 0..n | with the possibility to upload files |  |
| Reference Files/Schemas | URL | 0..n |  |  |
| Additional Description | Text Area | 0..1 | Additional Information on Reference Files/Schemas |  |
| ConditionForUse/Notes | Text Area | 0..1 |  | https://w3id.org/mobilitydcat-ap/conditions-for-access-and-usage |
| Data update frequency | Text Field | 0..1 | Controlled vocab in mobilityDCAT spec but simple text input no validation for now | https://w3id.org/mobilitydcat-ap/update-frequency |
| Temporal Coverage | Date | 0..2 | start and stop date, it should be possible to select just one attribute. |  |

### Changes to existing DCAT
| Existing | New |
| --- | --- |
| http://w3id.org/mds#dataCategory | https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category |
| http://w3id.org/mds#dataSubcategory | https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category |
| http://w3id.org/mds#dataModel | https://w3id.org/mobilitydcat-ap/mobility-data-standard |
| http://w3id.org/mds#geoReferenceMethod | https://w3id.org/mobilitydcat-ap/georeferencing-method |
| http://w3id.org/mds#transportMode | https://w3id.org/mobilitydcat-ap/transport-mode |

**Comment by richardtreier** [comment]
See also https://github.com/mobilityDCAT-AP/mobilityDCAT-AP

**Comment by ip312** [comment]
Thank you @kulgg .
I would suggest to use  https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/1.0.0/index.html#location-geographic-identifier for the NutsLocation and https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/1.0.0/index.html#location-geographic-name for the geoLocation to be aligned with mobilityDCAT.

**Comment by kulgg** [comment]
@ip312 Thanks you for that information! I extracted the mapping concerns to the new issue https://github.com/sovity/edc-extensions/issues/746

**Comment by ip312** [comment]
Both fields `referenceFilesDescription` and `conditionsForUse` are intended for lengthy texts. Should we use the same DCAT attribute? Perhaps Literal?

**Comment by kulgg** [comment]
@ip312 I used rdfs:label for conditionsForUse because it is given as a URI in https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/1.0.0/index.html#rights-statement-additional-information-for-access-and-usage

There exists the `+Additional information for access and usage` property for Rights Statement but as far as I understand it you cannot use this directly as a URI. To implement that in JSON the @type would have to be set to dct:RightsStatement and then the `+Additional information for access and usage` property field can be set. Afaik, this would break our current way of dealing with property fields as we just use direct URLs.

The same issue applies to the properties you linked above.

Correct me if I'm wrong @richardtreier 
We have to further analyze this internally

**Comment by richardtreier** [comment]
- We can't use `@type` unfortunately, as the Eclipse EDC is using that concept for its own purposes, and we can't easily acces sthat.
- We can't use the class `Dataset` as it's provided by the EDC and we can't override fields on it by providing them in the Asset JSON-LD
- We should try to map the complex object structure e.g. property1 -> property2 and build a JSON-LD object like that.
- Maybe we should post an example JSON-LD here to further visualize it.
