### ISSUE TITLE
Implement the new asset input screen with tabs

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#603]
# Feature Request

## Description

New layout for the input screen: implement the new asset input screen with tabs, with the most important (and all mandatory) offers in the main tab and optional offers in other tabs.

> _A clear and concise description of what the customer wants to happen._
> 
> -   As a USER who PRECONDITIONS, I want to DO_THING, so I can ACCOMPLISH_GOAL.
> 

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_What problems does that user face that existing functionalities do solve?_

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

## Stakeholders
- MDS
- @jkbquabeck 
- @SebastianOpriel 
- @sebk46 

## Solution Proposal and Work Breakdown

_If possible, provide a (brief!) solution proposal._

-   [ ] Step 1
-   [ ] Step 2
-   ...

**Comment by SebastianOpriel** [comment]
Duplicate of https://github.com/sovity/edc-ui/issues/89

**Comment by AbdullahMuk** [comment]
Will be resolved with https://github.com/sovity/edc-ui/issues/89
