### ISSUE TITLE
Documentate Keycloak DAPS vs Omejdn DAPS Settings

### ISSUE THREAD

**Issue by efiege** [sovity/edc-extensions#608]
# Feature Request

## Description

Omejdn:
`EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL`
`EDC_OAUTH_ENDPOINT_AUDIENCE: idsc:IDS_CONNECTORS_ALL`

Keycloak:
`EDC_OAUTH_PROVIDER_AUDIENCE: {{ Keycloak_Token_Url }}`
`EDC_OAUTH_ENDPOINT_AUDIENCE: idsc:IDS_CONNECTORS_ALL`

## Which Areas Would Be Affected?

https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/production/README.md

**Comment by tmberthold** [comment]
Note: as soon as the additional docu is in the linked deployment guide above, it is also referenced in our sovity EDC docu

**Comment by AbdullahMuk** [comment]
Resolved in https://github.com/sovity/edc-extensions/releases/tag/v6.0.0

**Comment by SebastianOpriel** [comment]
@AbdullahMuk just a remark: To have it in the release notes is not sufficient IMO
