### ISSUE TITLE
p12 legacy encryption

### ISSUE THREAD

**Issue by sebplorenz** [sovity/edc-extensions#62]
When generating the jks file out of the p12 using the get_client.sh we had the following error:

```
$ ./get_client.sh dwd-connector.test.mobilitydataspace.io.p12 thepassword
Error outputting keys and certificates
40A7D2E2ED7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not read certificate from ./cert.crt
Unable to load certificate
:
```

We had to add a -legacy switch in the first openssl command (line 22) for the script to work.

So that:

https://github.com/sovity/edc-extensions/blob/a4747da43c45cff285a2a4e66aa2a7cf48d70b48/resources/docs/get_client.sh#L22

becomes:

openssl pkcs12 -in "$P12_FILE" -clcerts -nokeys -legacy -out "$CRT_FILE" -passin "pass:$PASSWORD"

**Comment by omarsilva1** [comment]
It seems that you are on a newer version of openssl, since -legacy was only added in version 3.x. Since both versions (1.1.1 and 3.x) are LTS and being maintained I'll extend the script to check the version and in the case of 3.x add the -legacy tag.
