### ISSUE TITLE
Implement ability to update existing policies' ID

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-extensions#627]
# Feature Request

## Description

As a USER of the EDC, I want to edit my policies' ID, so I can keep the policies up-to-date or correct typos/ incorrect information in the description.

**The request is similar to https://github.com/sovity/edc-extensions/issues/606, focusing on policy management.** 

## Which Areas Would Be Affected?

- Solution should be implemented across all variants of the sovity CaaS EDC (sovity, MDS, Catena). Not only MDS variant. 
- Solution should be implemented across all subscription tiers of the sovity CaaS EDC (CE?, Basic, Professional, Enterprise). **TBC with stakeholders.**

## Why Is the Feature Desired?

> _What problems does that user face that existing functionalities do solve?_

As a user of the EDC I do not want to delete a policy and create a new one to change the description. (Additional steps for existing contract offers necessary as well)

As-Is Situation:

- User does not have the possibility to edit a policy.
- When a user wants to add additional information to an existing policy, user needs to delete the existing version of the policy and create a new policy.

## How does this tie into the current product?

> _Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

- Solution for this feature will be an enhancement to the UX of the existing policy management in sovity CaaS EDC.
- Solution is technical feasible based on the insights gathered in https://github.com/sovity/edc-ui/issues/400

## (For sovity Team to complete) Stakeholders

_Add more on who asked for this, i.e. company, person, how much they pay us, what their tier is, are they a strategic account, etc. Who needs to be kept up-to-date about this feature?_

- MDS
- @jkbquabeck 
- @AbdullahMuk 
- @SebastianOpriel 
- @sebk46

## (For sovity Team to complete) Solution Proposal and Work Breakdown

_If possible, provide a (brief!) solution proposal._

-   [ ] Step 1
-   [ ] Step 2
-   ...

## (For sovity Team to complete)  Need for refinement

> _Which questions are open? From whom do you need more input to fully specify the epic?_

-   Has MDS communicated insights on how many customers experience pain with the current situation? @jkbquabeck further insights would be required to assess the feasibility / necessity of this request. 
    - 5 out 40 customers experience (13% of surveyed users are affected) 
-   In what scenario has MDS users raised this request as value-add over the current situation? @jkbquabeck further insights would be required to assess the feasibility / necessity of this request. 
- In the next 6 months, is there the possibility that the meta data for policy is extended beyond just the policy ID?
-   ...

**Comment by AbdullahMuk** [comment]
@richardtreier can you please work on the solution proposal and effort estimation.

Please note that the request  is similar to https://github.com/sovity/edc-extensions/issues/606, focusing on policy management.

**Comment by SebastianOpriel** [comment]
As a suggestion: We could focus on editing non-relevant fields for the actual policy enforcement. This might reduce complexity

**Comment by AbdullahMuk** [comment]
From a product positioning perspective, to what extent do we want to create complexity in managing policies that are used in actively contracted data offers?

As a compromise:
- What we can offer is the editing of policies that are not used in actively contracted data offers.

**Comment by jkbquabeck** [comment]
To be clear: the editing of policies in this feature request does not concern the contents and effects of the policy, but the description/meta data, if that is the underlying issue here.

**Comment by AbdullahMuk** [comment]
To Do:
Abdullah works with Richard and Time on a concrete plan

Including...
- Step by step guide in the MDS guide
- Define how that guide should be updated the next time
- Provide MDS with the docker-compose (M400 > M600)

**Comment by jkbquabeck** [comment]
After aligning with MDS, this feature request can be closed and shall not be developed.
