### ISSUE TITLE
(edc-dev) Failed negotiating contract

### ISSUE THREAD

**Issue by darxsky** [sovity/edc-extensions#647]
# Bug Report

## Description

When a consumer wants to negotiate a contract with the data provider, an error occurs. In particular, the contract negotiation fails due to invalid consumer identity.

In my case: 
- Provider: http://edc2:11003/api/dsp
- Consumer: http://edc:11003/api/dsp
- UI Provider: http://localhost:22000/dashboard
- UI Consumer: http://localhost:11000/dashboard

### Expected Behavior

Contract agreement created.

### Observed Behavior
Contract negotiaton error (Invalid consumer identity)

``` ContractNegotiation: ID c6c32a94-3535-443b-a250-92879a057a34. Fatal error while [Consumer] Send ContractRequestMessage message. Error details: {"@type":"dspace:ContractNegotiationError","dspace:code":"400","dspace:reason":"Contract offer is not valid: Invalid consumer identity","@context":{"dct":"https://purl.org/dc/terms/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"https://www.w3.org/ns/dcat/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}} ```

## Steps to Reproduce

1. Go to Catalog Browser of the first connector to retrieve the available assets.

<img width="961" alt="CatalogBrowser" src="https://github.com/sovity/edc-extensions/assets/101062940/a9b849ff-2c46-4ca4-8035-e717a24b1f15">

2. Click on the available asset.

<img width="958" alt="AssetDetails" src="https://github.com/sovity/edc-extensions/assets/101062940/2a7c5cfa-d1c8-4c5f-81db-9aea8e1f908e">

3. Click on Negotiate button.

![FaildeNegotiatingContract](https://github.com/sovity/edc-extensions/assets/101062940/4829c318-7fad-44bf-9607-16172b490b07)

4. See error "Failed negotiating contract".

## Context Information

-   Used version
        edc: ```ghcr.io/sovity/edc-dev:latest```
        edc-ui: ```ghcr.io/sovity/edc-ui:2.1.0```
-   Logs: 
        ``` ContractNegotiation: ID c6c32a94-3535-443b-a250-92879a057a34. Fatal error while [Consumer] Send ContractRequestMessage message. Error details: {"@type":"dspace:ContractNegotiationError","dspace:code":"400","dspace:reason":"Contract offer is not valid: Invalid consumer identity","@context":{"dct":"https://purl.org/dc/terms/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"https://www.w3.org/ns/dcat/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}} ```
-   OS: ```Linux, Windows```

## Possible Implementation and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine a Solution Proposal / Work Breakdown
```

**Comment by richardtreier** [comment]
Fix implemented in https://github.com/sovity/edc-extensions/pull/642, please await the upcoming release.
