### ISSUE TITLE
CI:  Fix CodeQL

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#678]
# Bug Report

## Description

The main is currently red. That's not good.

## Solution Proposal & Breakdown

```[tasklist]
### Tasks
- [ ] CodeQL: What is it, do we still need it, do we fix it, etc.
- [ ] Make main green again.
```

**Comment by tmberthold** [comment]
Just because I randomly saw it, there's a PR open fixing that: https://github.com/sovity/edc-extensions/pull/670
