### ISSUE TITLE
Custom Asset JSON-LD is a trap right now

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#679]
# Feature

## Description

Our UiAsset has the properties `additionalProperties`, `additionalJsonProperties`, `privateProperties` and `privateJsonProperties`.

These properties are called "Json" but are JsonLd and affected by compaction and contraction, e.g. all propreties that aren't URLs disappear, strings become arrays, etc.

Any API consumer that wants to do anything "custom" such as a use case will stumble upon this

## Proposed Solution

- [x] Property `String customJson` 
  - [x] Will be put in the JSON-LD as `sovity:customJson: "{{JSON STRINGIFIED}}"
  - [x] So it won't be affected by compaction / extraction / JSON-LD validation, etc.
  - This would be used by technical users who want to largely diverge from our UI's way of defining assets, and also don't care about JSON-LD as they are owning the data space they use.
- [ ] Property `Map<String, String> customProperties`
  - [ ] Simply easier access to all fields of "customJson" that are strings.
  - [ ] The above needs to be documented.
  - [ ] This is sort of easy access to custom data when you don't want to deal with JSON serialization / deserialization
  - [ ] Will be merged with customJson on persisting
  - [ ] Only string propreties get put in this map on reading `sovity:customJson`.
  - As above it is an easy entry for people to add custom fields and data to assets, e.g. realizing a use case within a data space.
- [x] Property `String customJsonLd`
  - [x] Should contain the remainder of the unhandled JSON-LD of the Asset JSON-LD (as the customJson above is just one field that we control)
  - [x] Will be rocked by compaction / expansion
  - [x] Is documented as JSON-LD so everybody who uses it has JSON-LD semantic parsing utilities ready
  - Useful for people who want to adhere to some JSON-LD standard that forces them to adhere to some ontology. However, support for this would be experimental.
  - More than anything this is a place to find out if something weird was set into the asset

## Possible Implementation and Work Breakdown

```[tasklist]
- [x] Implement changes in UiAsset and UiAssetMapper
- [ ] https://github.com/sovity/edc-extensions/issues/852
```

**Comment by richardtreier** [comment]
Maybe related: https://github.com/sovity/edc-ui/issues/545

**Comment by AbdullahMuk** [comment]
blocked by https://github.com/sovity/edc-extensions/issues/852.

once https://github.com/sovity/edc-extensions/issues/852 is resolved, we can close this issue.
