### ISSUE TITLE
[Backend] Convert MDS fields to mobilityDCAT-AP

### ISSUE THREAD

**Issue by kulgg** [sovity/edc-extensions#746]
# Feature Request

## Description
(Extracted from: https://github.com/sovity/edc-extensions/issues/602)

As a a shareholder of the MDS I want existing and newly added MDS specific attributes to use the property keys outlined in the mobilityDCAT-AP specification wherever possible.

Currently placeholder values are used for the new fields and the existing fields are mapped to mobilityDCAT controlled vocabulary URIs which may not be optimal.

The current mapping to mobilityDCAT-AP follows. It may need changes after coordination with MDS.

| Name | Data Type | Cardinality | Notes | DCAT |
|---|---|---|---|---|
| sovereignLegalName  |  Text Field |  0..1  |  The sovereign is distinct from the publisher by being the legal owner of the data. | dcat:Dataset > dct:rightsHolder (+rights holder) |
| geoLocation| Text Field  |  0..1 |   | dcat:Dataset > dct:spatial > skos:prefLabel (+geographic name) |
| nutsLocation |  Text Field | 0..n  | Locations by NUTS standard which divides countries into administrative divisions |  dcat:Dataset > dct:spatial > dct:identifier (+geographic identifier) |
| dataSampleUrls | URL | 0..n | | dcat:Dataset > dcat:Distribution > adms:sample (+sample) (Moved to dcat:Dataset in 2.0.1)  |
| referenceFileUrls | URL | 0..n | Reference file/schema URLs | dcat:Dataset >  dcat:Distribution > mobilitydcatap:mobilityDataStandard > mobilitydcatap:schema (+schema) > dcat:downloadURL |
| referenceFilesDescription | Text Area | 0..1 | Additional Information on Reference Files/Schemas | dcat:Dataset >  dcat:Distribution > mobilitydcatap:mobilityDataStandard > mobilitydcatap:schema (+schema) > rdfs:Literal |
| conditionsForUse | Text Area | 0..1 |  | dcat:Dataset >  dcat:Distribution > dct:RightsStatement > rdfs:label (+Additional information for access and usage) |
| dataUpdateFrequency | Text Field | 0..1 | Controlled vocab in mobilityDCAT spec but simple text input no validation for now | dcat:Dataset > dct:accrualPeriodicity |
| temporalCoverageFrom | Date | 0..1 | start date | dcat:Dataset > dct:temporal (temporal coverage) > dcat:startDate |
| temporalCoverageToInclusive | Date | 0..1 | end date |  dcat:Dataset > dct:temporal (temporal coverage) > dcat:endDate |

### Changes to existing DCAT
| Existing | New |
| --- | --- |
| http://w3id.org/mds#dataCategory | dcat:Dataset > mobilitydcatap:mobilityTheme > https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category |
| http://w3id.org/mds#dataSubcategory | dcat:Dataset > mobilitydcatap:mobilityTheme > https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category |
| http://w3id.org/mds#dataModel | dcat:Dataset > dcat:Distribution > mobilitydcatap:mobilityDataStandard |
| http://w3id.org/mds#geoReferenceMethod | dcat:Dataset > mobilitydcatap:georeferencingMethod |
| http://w3id.org/mds#transportMode | dcat:Dataset > mobilitydcatap:transportMode |

## (For sovity Team to complete) Solution Proposal and Work Breakdown

```[tasklist]
- [x] Clear up remaining questions regarding the mapping of the fields with MDS
- [x] Check if non-unique property keys break our current implementation handling asset properties (this might make this complex)
- [x] Align on to-dos related to JSON-LD as per Richard's comment: https://github.com/sovity/edc-extensions/issues/602#issuecomment-1910253710
- [x] Add test that verifies Dataset > Distribution field is not preoccupied by EDC
- [x] We should also add MEDIATYPE to distribution field as it now seems available
- [x] Add new properties to `Prop.java`
- [x] Replace usage of Prop for affected fields everywhere
- [ ] Write database migration changing the property key for affected fields
```

**Comment by kulgg** [comment]
@ip312 you can find the updated mapping integrating your changes above

**Comment by ip312** [comment]
Thank you @kulgg. It looks almost perfect, the last thing would be: is ist possible to change

**Comment by kulgg** [comment]
The publisher homepage field defacto contains the homepage and I think it would be inaccurate to change it to name @ip312

**Comment by AbdullahMuk** [comment]
Solution Proposal requires refinement to include JSON-LD elements as per [this comment](https://github.com/sovity/edc-extensions/issues/602#issuecomment-1910253710)

**Comment by kulgg** [comment]
The following fields need data migrations

```
{
  "http://www.w3.org/ns/dcat#distribution": {
    "http://www.w3.org/ns/dcat#mediaType": "http://www.w3.org/ns/dcat#mediaType",
    "https://w3id.org/mobilitydcat-ap/mobilityTheme/mobilityDataStandard": {
      "@id": "previously http://w3id.org/mds#dataModel"
    }
  },
  "https://w3id.org/mobilitydcat-ap/mobilityTheme": {
    "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-category": "previously http://w3id.org/mds#dataCategory",
    "https://w3id.org/mobilitydcat-ap/mobility-theme/data-content-sub-category": "previously http://w3id.org/mds#dataSubcategory"
  },
  "https://w3id.org/mobilitydcat-ap/georeferencingMethod": "previously http://w3id.org/mds#geoReferenceMethod",
  "https://w3id.org/mobilitydcat-ap/transportMode": "previously http://w3id.org/mds#transportMode"
}
```

**Comment by ununhexium** [comment]
@kulgg code: LGTM.
@richardtreier could you review the workaround to disable the tests that fail on GH only?
