### ISSUE TITLE
Ambiguity of the environment settings

### ISSUE THREAD

**Issue by ip312** [sovity/edc-extensions#8]
# Bug Report

## Describe the Bug
The documentation says _The **test** environment is set by default._, but presents **dev** enivronment links.
The docker compose file contains **test** environment links.

### Expected Behavior
Only one environement (dev) shall be used at this stage.

**Comment by SebastianOpriel** [comment]
dev environment is only accessible by developers of MDS. As this repository is designated to be used by users of MDS, the test environment shall be used instead of dev.

**Comment by SebastianOpriel** [comment]
@omarsilva1 please change the values back to `dev`
