### ISSUE TITLE
Client ID example in Readme is inconsistent

### ISSUE THREAD

**Issue by sebplorenz** [sovity/edc-extensions#86]
# Bug Report

## Description

The FAQ section shows this client id example:

```EDC_OAUTH_CLIENT_ID: 7X:7Y:...:B2:94:keyid:6A:2B:...:28:80```

but the /get_client.sh script does not put a keyid between ski and aki.

Also it is described that the user should:

```Copy the SKI:AKI combination and use it to start the EDC```

This is inconsistent. Because if the key is just copied, it will not contain a keyid.

### Expected Behavior

The readme should be consistent with the get_client.sh script output.

**Comment by tmberthold** [comment]
> but the /get_client.sh script does not put a keyid between ski and aki.

Works for me though:
![image](https://user-images.githubusercontent.com/75306992/216566356-e6f21263-af44-453d-bce4-38a05e193ce5.png)

We're going to look at this more closely anyway.

**Comment by tmberthold** [comment]
Will close it until we get feedback. If it still does not work, just reopen the ticket.
