### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9191 post running postman_collection.json file

### ISSUE THREAD

**Issue by KeshavFH** [sovity/edc-extensions#88]
# Bug Report

## Description

Getting error while running the postman_collection.json file: "Error: connect ECONNREFUSED 127.0.0.1:9191" along with "Forbidden" when visiting ""https://daps.dev.mobility-dataspace.eu/jwks.json"".

### Expected Behavior

The broker extension should be attached and published.
## Context Information

_Add any other context about the problem here._

-   Environment: Which instance or deployment were you using when the error occurred? Staging, Productive, Connector-URL, etc.?
-   Used version: If a specific component was used, which Version did you use? E.g. EDC v1.0.0
-   Time: When did the error occur? Exact timestamp (incl. time zone; assumed CET/CEST if missing) if possible.
-   Logs: Error log or further information
-   Parameter: Request contents or information entered
-   OS: [e.g. iOS, Windows]
-   ...

## Possible Implementation and Work Breakdown

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

-   [ ] Task 1
-   [ ] Task 2
-   ...
![Screenshot 2023-02-05 110938](https://user-images.githubusercontent.com/123020210/216813490-204b3c18-8f85-4cc6-9882-bd220e9d7e17.png)
![Screenshot 2023-02-05 111258](https://user-images.githubusercontent.com/123020210/216813492-e0dbf75a-ef07-4801-bb33-b1557c908174.png)

**Comment by tmberthold** [comment]
The Postman Collection seems to be outdated, the ports of the example docker-compose have changed in the meantime. Will take a look.

However, the URL of the MDS works for me.

**Comment by ip312** [comment]
@KeshavFH Two points from my side.
1) To have possibility to test this extension in a MDS environment you need to obtain a MDS certificate, i.e. to be a MDS participant.
2) Generally there is no access for the MDS dev-environment for MDS particpants. Our intention was primarily to use this docker compose for internal tests. Now we are moving on to the next stage and will change dev environment links through test environment links. Then all our participants would have possibility to test and deploy the MDS EDC extensions.
Alternatively you can fix links manually, but you will still need a valid MDS certificate.
