### ISSUE TITLE
Update Connector Description

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-extensions#9]
If Connector Name, Curator and Maintainer are adjusted in docker-compose,, the old values still seem to be visible in the broker.

**Comment by tmberthold** [comment]
Should not actually be the case, the latest data is always read and sent to the broker as ConnectorUpdateMessage:
https://github.com/sovity/edc-broker-extension/blob/3dfeb2388a6942dd49d27a9898b5fd02eb4d3e70/extensions/catalog-transfer-extension/src/main/java/catalogtransfer/broker/IdsBrokerServiceImpl.java#L60

**Comment by omarsilva1** [comment]
On thursday we got the feedback that it is still not possible to update the description of the EDC. The previous PR fixed only setting the title, maintainer and curator.

**Comment by ip312** [comment]
Currently there are three attributes in the docker compose file: EDC_IDS_TITLE, EDC_IDS_DESCRIPTION, EDC_CONNECTOR_NAME. An update of the last one changes the name field in the broker.
Changes of first two seem currently to have no impact for the broker presentation.

**Comment by omarsilva1** [comment]
The title has no meaning in the broker. To change the "title" you can use the EDC_CONNECTOR_NAME field. 

I've created a PR that fixes the description.
